@startuml
class AdminGroup{
+handle($request, Closure $next)
}
class PostController extends Controller{
+index()
+create()
+store(CreatePostRequest $request)
+delete(Request $request)
+show($id)
+destroy($id)
}

class FacultyController extends Controller{
+index()
+create()
+store(Request $request)
+delete(Request $request)
+show($id)
+destroy($id)
}

class GroupController extends Controller{
+index()
+create()
+store(Request $request)
+delete(Request $request)
+show($id)
+destroy($id)
}

class PolicyController extends Controller{
+index()
+create()
+store(Request $request)
+delete(Request $request)
+show($id)
+destroy($id)
}

class SpecialityController extends Controller{
+index()
+create()
+store(Request $request)
+delete(Request $request)
+show($id)
+destroy($id)
}

class UserController extends Controller{
+index()
+create()
+store(Request $request)
+delete(Request $request)
+show($id)
+destroy($id)
}

class ReferenceController extends Controller{
+index()
+create()
+store(CreateReferenceRequest $request)
+delete(Request $request)
+show($id)
+destroy($id)
}

class Controller extends BaseController

class HomeController extends Controller {
+__construct()
+index()
}



class Faculty extends Model{
#$table
#$fillable
+getName()
}
class Group extends Model{
#$table
#$fillable
+getNumber()
+speciality()
+faculty()
}

class Policy extends Model{
#$table
#$fillable
+owner()
}

class Post extends Model{
#$table
#$fillable
+setUserIdAttribute($value)
+owner()
}

class Reference extends Model{
#$table
#$fillable
+user()
}

class Speciality extends Model{
#$table
#$fillable
+getName()
+getDescription()
}

class User extends Model{
#$table
#$fillable
#$hidden
+group()
+references()
+posts()
+role()
+hasRole($role = 'admin')
+isAdmin()
+isStudent()
+isTeacher()
}


class CreateReferenceRequest extends FormRequest{
+rules()
}

class CreatePostRequest extends FormRequest{
+rules()
}


class ExampleTest extends TestCase
@enduml