@startuml

package "Web Client Machine" {
[ClientGUI]
}

package "Web Server" {
[Router]
[PostController]
[FacultyController]
[GroupController]
[PolicyController]
[SpecialityController]
[ReferenceController]
[PageControllers]
[MySQL]
}

[ClientGUI] --> [Router] : Http
[Router] --> [PostController]
[Router] --> [FacultyController]
[Router] --> [GroupController]
[Router] --> [PolicyController]
[Router] --> [SpecialityController]
[Router] --> [ReferenceController]
[Router] --> [PageControllers]
[PostController] --> [MySQL]
[FacultyController] --> [MySQL]
[GroupController] --> [MySQL]
[PolicyController] --> [MySQL]
[SpecialityController] --> [MySQL]
[ReferenceController] --> [MySQL]
@enduml